---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mario
    sparkfabrik.com/game: mario
  name: mario
  namespace: games
spec:
  ports:
    - name: vnc
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: audio
      port: 8081
      protocol: TCP
      targetPort: 8081
  type: LoadBalancer